# Generated by Django 4.0.4 on 2022-05-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Id_No', models.IntegerField()),
                ('Address', models.TextField()),
                ('Mobile_No', models.BigIntegerField()),
                ('Emp_Role', models.CharField(max_length=100)),
            ],
        ),
    ]
